export const DemoData = [
  {
    firstName: 'William1',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Books',
  },
  {
    firstName: 'One1',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Color',
  },
  {
    firstName: 'Two1',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi1',
    lastName: 'Saxena',
    address: 'England',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick1',
    lastName: 'Jonas',
    address: 'England',
    wishes: 'Games',
  },
  {
    firstName: 'Testing1',
    lastName: ' Name',
    address: 'England',
    wishes: 'Bicycle',
  },
  {
    firstName: 'One1',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Color',
  },
  {
    firstName: 'Two1',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi1',
    lastName: 'Saxena',
    address: 'England',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick1',
    lastName: 'Jonas',
    address: 'England',
    wishes: 'Games',
  },
  {
    firstName: 'Testing1',
    lastName: ' Name',
    address: 'England',
    wishes: 'Bicycle',
  },
  {
    firstName: 'William',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Books',
  },
  {
    firstName: 'One',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Color',
  },
  {
    firstName: 'Two',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi',
    lastName: 'Saxena',
    address: 'England',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick',
    lastName: 'Jonas',
    address: 'England',
    wishes: 'Games',
  },
  {
    firstName: 'Testing',
    lastName: ' Name',
    address: 'England',
    wishes: 'Bicycle',
  },
  {
    firstName: 'One',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Color',
  },
  {
    firstName: 'Two',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi',
    lastName: 'Saxena',
    address: 'England',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick',
    lastName: 'Jonas',
    address: 'England',
    wishes: 'Games',
  },
  {
    firstName: 'Testing',
    lastName: ' Name',
    address: 'England',
    wishes: 'Bicycle',
  },
  {
    firstName: 'Two',
    lastName: 'Shakespeare',
    address: 'England',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi',
    lastName: 'Saxena',
    address: 'England',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick',
    lastName: 'Jonas',
    address: 'England',
    wishes: 'Games',
  },
  {
    firstName: 'Testing',
    lastName: ' Name',
    address: 'England',
    wishes: 'Bicycle',
  }
];
