export const DemoData = [
  {
    firstName: 'Will',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Books',
  },
  {
    firstName: 'One1',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Color',
  },
  {
    firstName: 'Two1',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi1',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick1',
    lastName: 'Jonas',
    address: 'Eng',
    wishes: 'Games',
  },
  {
    firstName: 'Test1',
    lastName: ' Name',
    address: 'Eng',
    wishes: 'Bicycle',
  },
  {
    firstName: 'One1',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Color',
  },
  {
    firstName: 'Two1',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi1',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick1',
    lastName: 'Jonas',
    address: 'Eng',
    wishes: 'Games',
  },
  {
    firstName: 'WillTest1',
    lastName: ' Name',
    address: 'Eng',
    wishes: 'Bicycle',
  },
  {
    firstName: 'Will',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Books',
  },
  {
    firstName: 'One',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Color',
  },
  {
    firstName: 'Two',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick',
    lastName: 'Jonas',
    address: 'Eng',
    wishes: 'Games',
  },
  {
    firstName: 'Test',
    lastName: ' Name',
    address: 'Eng',
    wishes: 'Bicycle',
  },
  {
    firstName: 'One',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Color',
  },
  {
    firstName: 'Two',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick',
    lastName: 'Jonas',
    address: 'Eng',
    wishes: 'Games',
  },
  {
    firstName: 'Test',
    lastName: ' Name',
    address: 'Eng',
    wishes: 'Bicycle',
  },
  {
    firstName: 'Two',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pen',
  },
  {
    firstName: 'Rashi',
    lastName: 'S',
    address: 'Eng',
    wishes: 'Pencil',
  },
  {
    firstName: 'Nick',
    lastName: 'Jonas',
    address: 'Eng',
    wishes: 'Games',
  },
  {
    firstName: 'Test',
    lastName: ' Name',
    address: 'Eng',
    wishes: 'Bicycle',
  }
];
